version: '3'
services:
  k8s-springboot-demo:
    image: yangqiuhua/k8s-springboot-demo:latest
    container_name: k8s-springboot-demo
    ports:
      - "8070:8090"
    environment:
      - server.port=8090
      - logging.level.root=DEBUG
      - logging.file.name=/data/logs/k8s-springboot-demo/k8s-springboot-demo.log
#linux 宿主机data/logs目录挂载到容器data/logs目录
#    volumes:
#      - "/data/logs:/data/logs
#windows 宿主机E盘data/logs目录挂载到容器data/logs目录
#    volumes:
#      - "E:\data\logs:/data/logs"