apiVersion: v1
kind: Service
metadata:
  name: k8s-springboot-demo
  labels:
    app: k8s-springboot-demo
spec:
  type: NodePort
  ports:
  - port: 8090
    nodePort: 30090
    targetPort: 8090
  selector:
    app: k8s-springboot-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-springboot-demo
  labels:
    app: k8s-springboot-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-springboot-demo
  template:
    metadata:
      labels:
        app: k8s-springboot-demo
    spec:
      containers:
      - name: k8s-springboot-demo
        image: yangqiuhua/k8s-springboot-demo:latest
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
        env:
        - name: server.port
          value: "8090"
        - name: logging.level.root
          value: "DEBUG"
        - name: logging.file.name
          value: "/data/logs/k8s-springboot-demo/k8s-springboot-demo.log"
        volumeMounts:
        - name: k8s-springboot-demo
          mountPath: /data
      volumes:
      - name: k8s-springboot-demo
        hostPath:
          path: /data
          type: DirectoryOrCreate
